services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    ############################################################################
    # SERVICES                                                                 #
    ############################################################################

    HBM\UserBundle\Service\UserPasswordPolicyHelper:
        arguments:
            $config: '%hbm.user.password_policy%'

    hbm.user.password_policy:
        alias: HBM\UserBundle\Service\UserPasswordPolicyHelper

    ############################################################################
    # VALIDATION                                                               #
    ############################################################################

    HBM\UserBundle\Validator\Constraints\PasswordPreviouslyUsedValidator:
        tags:
            - { name: validator.constraint_validator }
